### ISSUE TITLE
skipping package - unexpected packet_size - length: 124

### ISSUE THREAD

**Issue by robin-gdwl** [Mandelbr0t/UniversalRobot-Realtime-Control#1]
Hello, first of all thank you for your work on the code. It works absolutely flawwlessly when I use it with UR-Sim. however, on a real robot i frequently get this error: 

`skipping package - unexpected packet_size - length: 124`
or this one: 
`skipping package - unexpected packet_size - length: 16384`

I am using Polyscope version  3.7.2.40245, which version did you use during developement?
As you can see in the screenshot from debugging, the package_size is gigger then the buffer_length which causes an error and the package is not decoded.

Any idea what could be going on here? any help would be greatly appreciated.

![Screenshot 2020-02-01 at 21 19 58](https://user-images.githubusercontent.com/25942644/73598436-a495fe80-4538-11ea-9734-4218c2b2d182.jpg)

**Comment by Mandelbr0t** [comment]
Hi Robin, nice that this helped you :)
The code is based on 3.2, maybe 3.4 i'm not entirely sure anymore and should've written that down.
I have to finish some exams currently so no real time, but my suggestion would be to check the rtde communication for your version or downgrade. Can you use the functions in UrScript.py at all? 
Let me know your solution

**Comment by robin-gdwl** [comment]
Thanks for your answer, I did some more tests and it turns out that its probably not the version that is causing problems. 
Instead it is the connection between robot and my computer. 
My code always works after restarting the robot but doesnt when I try running it a second time, thats when the error occurs. My guess now is that the connection is never properly closed  ( my code terminates due to an error or Keyboard interrupt) so it cant always connect a second time. 
I will try it out if closing the connection gets rid of the problem and will report my results .

**Comment by robin-gdwl** [comment]
Yes, the issue was caused by some connection on the robot not being properly closed... totally my fault. 
Thanks again for your work and quick response. Here you can see what I did with it: https://github.com/boundlessmaking/UR_Facetracking  however, the code is a mess at the moment so please dont judge :D
