### ISSUE TITLE
blend radius when moving between poses not working

### ISSUE THREAD

**Issue by m4ln** [Mandelbr0t/UniversalRobot-Realtime-Control#2]
Hey, thank you so much for providing this amazing package, it's very helpful for doing real-time movements without the need of using the control panel. 
Now we try to do a simple movement between TCP poses using `movel()` or `movej()` using a blend radius > 0, i.e to get a smooth movement and don't stop at every pose.
However, if we increase the blend radius to (e.g r =0.05), the robot stops very abruptly at each point (you can also hear the breaks very clearly). I attached two videos showing the difference between r=0 and r=0.05.
We use the UR3e and Polyscope v. 5.12.
Do you have any idea what the problem is or how we can solve this?

https://github.com/Mandelbr0t/UniversalRobot-Realtime-Control/assets/31984397/7dbdfcc6-f98e-44ea-bdc5-1875be206f7b

https://github.com/Mandelbr0t/UniversalRobot-Realtime-Control/assets/31984397/ec0b1399-1af8-4dd1-ba7c-b528cbac83a7

**Comment by Mandelbr0t** [comment]
The approach in this repository does not use movej or movel because of the mentioned issues, but the command servoj. This way no new program has to be sent to the robot and the robot can perform a smooth trajectory.

**Comment by m4ln** [comment]
But still, I don't understand why changing the blend radius gives that result, like why it makes a difference, so it seems UR internally does something...?
Anyway we could find another solution by modifying the `move_waypoints()` function, which wasn't working before.
Thank you for the fast reply!
